server:
  port: 8080 

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8099/eureka/
      defaultZone: http://registry-service:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
      
      routes:
        # Ruta para "ms-pedidos"
        - id: ms-pedidos-route
          uri: lb://ms-pedidos  # busca en Eureka"
          predicates:
            - Path=/api/pedidos/** 
        
        # Ruta para "ms-productos"
        - id: ms-productos-route
          uri: lb://ms-productos
          predicates:
            - Path=/api/productos/** 

        # AUTH SERVER (Endpoints de Token) 
        - id: ms-authorization-server-oauth
          uri: lb://MS-AUTHORIZATION-SERVER #  Eureka
          predicates:
            - Path=/oauth2/** # Redirige /oauth2/token, /oauth2/authorize, 

        #  AUTH SERVER (Configuración OIDC) 
        - id: ms-authorization-server-well-known
          uri: lb://MS-AUTHORIZATION-SERVER #  Eureka
          predicates:
            - Path=/.well-known/** # Redirige la validacion tokens

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://gateway-service:8080