server:
  port: 9000

spring:
  application:
    name: ms-authorization-server
  cloud:
    config:
      uri: http://ms-config-server:8888
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8099/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: "never"
