server:
  port: 9000
  forward-headers-strategy: "framework"

spring:
  application:
    name: ms-authorization-server
  security:
    oauth2:
      authorizationserver:
        issuer: http://gateway-service:8080
  
eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8099/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: "never"
