server:
  port: 8082
spring:
  
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_pedidos_dev
    username: postgres
    password: 3264 
    pool:
      enabled: true
  
  sql:
    init:
      mode: always 


ms-productos:
  url: http://localhost:8081