server:
  port: 7081 # Puerto para Producción
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_productos_prd # BD de PRD
    username: postgres
    password: 3264 # 
    pool:
      enabled: true
  jpa:
    show-sql: false # Nunca mostrar SQL producción
logging:
  level:
    root: WARN # En producción, solo reportamos advertencias (WARN) o errores (ERROR)